version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./config/mongod.conf:/etc/mongo/mongod.conf:rw
      - ./config/initdb.d/:/docker-entrypoint-initdb.d/ #设置容器启动脚本
      - ./data/db:/data/db
    privileged: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=deploy
    networks:
      - mynetwork
    command: --auth
  frontend:
    image: deploy-docker-frontend:latest
    ports:
      - "8809:8080"
    networks:
      - mynetwork
    volumes:
      - ./data/html:/usr/ share/nginx/html/web
    depends_on:
      - backend
    restart: always
  backend:
    image: deploy-docker-backend:latest
    depends_on:
      - mongo
    networks:
      - mynetwork
    volumes:
      - ./data/projects:/home/deploy/projects
      - ./data/shell:/home/deploy/shell
      - ./data/html:/usr/share/nginx/html
      - ./data/.ssh:/home/.ssh
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
networks:
  mynetwork:
    driver: bridge